// models/Report.js
import mongoose from "mongoose";

const reportSchema = new mongoose.Schema(
  {
    reporterId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    reportedUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    reason: { type: String, required: true },
    status: { type: String, enum: ["pending", "reviewed", "resolved"], default: "pending" },

    // AI-ready fields
    aiSummary: { type: String, default: null },          // Summary generated by AI
    aiScore: { type: Number, default: null },            // Risk/priority score
    suggestedAction: { type: String, default: null },    // AI's recommended action
  },
  { timestamps: true }
);

export default mongoose.model("Report", reportSchema);